Code is refactored: redux/common folder is created; PokePage containe…
1babamanja1/shop pull request #7
Opened 2021-09-24 15:24 UTC by 1babamanja1

…r is created; import order fixed; code is divided into logical parts

2021-09-24 16:13 UTC, Vladislav-Rzheutskij requested changes

2021-09-24 16:13 UTC, Vladislav-Rzheutskij commented on src/Containers/Cart/Cart.jsx
> +  return (cart && cart.length > 0)
cart?.length

2021-09-24 16:13 UTC, Vladislav-Rzheutskij commented on src/Containers/Cart/Cart.jsx
> +          <div key={Math.random().toString(36).substring(5)}>
ууу это что такое?))

2021-09-24 16:13 UTC, Vladislav-Rzheutskij commented on src/Containers/Homepage/Homepage.jsx
>    const pokeListFromServer = useSelector(getPokes);
просто pokeList

2021-09-24 16:13 UTC, Vladislav-Rzheutskij commented on src/Containers/PokePage/PokePage.jsx
> +const PokePage = () => {
какой то это странный компонент, не вижу в нем смысла, лучше BigSaleCard так назови и перенеси в контейнеры

2021-09-24 16:13 UTC, Vladislav-Rzheutskij commented on src/Containers/PokePage/PokePage.jsx
> +  const pokeData = pokeList.find((item) => item.name === pokeName);
Сделай лучше запрос на сервер который тебе отдаст инфу по этому покемону

2021-09-24 16:13 UTC, Vladislav-Rzheutskij commented on src/redux/common/dataLoading/reducers.js
> -function pokeReducer(state = defaultState, action) {
ненене, оставь папку с покемонами, вынеси только загрузку и тему в отдельный общий объект

2021-09-27 08:43 UTC, 1babamanja1 commented on src/App.js
>    return (
Константа theme использует useSelector, поэтому если определить её вне провайдера, реакт ругается. Пока что умнее отдельного компонента я ничего не придумала.

2021-09-27 08:44 UTC, 1babamanja1 commented on src/Components/BigSaleCard/BigSaleCard.jsx
> +        {type.map((item) => Type(item, name))}
![image](https://user-images.githubusercontent.com/71030913/134874900-9fa0f915-b7bb-489a-958f-9a1ab82979f7.png)

2021-09-28 15:30 UTC, Vladislav-Rzheutskij requested changes

2021-09-30 13:10 UTC, Vladislav-Rzheutskij approved these changes

2021-09-30 14:18 UTC, merged